#%RAML 1.0 Library
usage: Library of DataTypes

types:
  Partner: !include ../datatypes/carPartner.raml
  Car: !include ../datatypes/car.raml
  Booking: !include ../datatypes/carBooking.raml
  Error: !include ../datatypes/Error.raml
  Status: !include ../datatypes/Status.raml